# Generated by Django 4.2.5 on 2025-06-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Programada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cita', to='ziara_app.citas')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('B', 'Barba'), ('C', 'Cabello'), ('R', 'Rostro'), ('N', 'Natural'), ('P', 'Cuerpo')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('duracion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('B', 'Barba'), ('C', 'Cabello'), ('S', 'Spa')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_comprados', to='ziara_app.pagos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziara_app.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('B', 'Barbero'), ('C', 'Cliente')], default='C', max_length=1)),
                ('horario_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ziara_app.perfiles'),
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_productos', to='ziara_app.productos')),
            ],
        ),
        migrations.CreateModel(
            name='CitaServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ziara_app.citas')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_servicio', to='ziara_app.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='citas',
            name='barbero',
            field=models.ForeignKey(limit_choices_to={'rol': 'B'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_barbero', to='ziara_app.perfiles'),
        ),
        migrations.AddField(
            model_name='citas',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='cita_cliente', to='ziara_app.perfiles'),
        ),
    ]
